version: '3'

services:
  ftpserver:
    build: './FTPServer'
    volumes:
      - /opt/Data:/go/App/Data
    network_mode: host

  traffic:
    build: './Analysis/Traffic'
    volumes:
      - /opt/Data:/go/App/Data
    container_name: trafficanalysis
    network_mode: host
